### ISSUE TITLE
Automatically refresh OAuth 2 token (do not jump to login screen on expiry)

### ISSUE THREAD

**Issue by hjacobs** [zalando/zmon-android#11]
The ZMON android app currently jumps back to the login screen every time the token expires (default: after 1 hour), we should either implement "real" OAuth 2 with a refresh token or automatically refresh the token in the background and only jump to the login screen in case of authentication failures.

I flag this as a bug, because I would consider jumping back to the login screen as "unexpected behavior".

**Comment by iweinzierl** [comment]
Should be fixed in 51e38390e5a303352d2896b412691eac870cc368 but needs some testing. OAuth access token is updated automatically when a new request is executed and a 401 is returned using username/password credentials if stored in the app.
