### ISSUE TITLE
Show alert details: entities and check values

### ISSUE THREAD

**Issue by hjacobs** [zalando/zmon-android#6]
Most important missing feature of the app: show full alert details including all entities in alert and check result values.

**Comment by hjacobs** [comment]
@iweinzierl committed a first version: entities and values are now shown on a separate tab :tada:

**Comment by iweinzierl** [comment]
Can we close this issue or do we need more here?

**Comment by hjacobs** [comment]
I think we can close it for now, I guess we will find out (by experience) what else we want to display in the alert details soon enough.
