### ISSUE TITLE
Improve display of push notifications 

### ISSUE THREAD

**Issue by iweinzierl** [zalando/zmon-android#8]
Right now, you are not even able to see the full name of an alert in a system notification. A click on the notification brings you to the dashboard with all alerts that are active at that moment. You don't have a chance to identify the alert from the notification any further. So, it would be nice to see at least the full name of the alert.

**Comment by iweinzierl** [comment]
Another idea: when the user clicks on a system notification, zmon app is started and the AlertDetail activity is displayed with the details of the alert that was pushed.

**Comment by MALPI** [comment]
+1

**Comment by iweinzierl** [comment]
Should be fixed in 97e00ef86e01cf087ddc83135f06562cf87718f0 but needs some testing.
